export class Utility{
  static preferencesName: string = 'water';
  static bigGlassDefaultName: string = 'big_glass_default';
  static smallGlassDefaultName: string = 'small_glass_default';
  static waterLevel: string = 'water_level';
  static bigGlassDefaultValue: number = 200;
  static smallGlassDefaultValue: number = 100;
  static unWateredState: number = 100;
  static midWateredState: number = 150;
  static sadGlass: number = 0;
  static neutralGlass: number = 1;
  static happyGlass: number = 2;
}